export const userlisadata =  [
  {
    userName: "JohnDoe",
    Phone: "5551234567",
    Email: "johndoe@example.com",
    fPass: "password123",
    cnfPass: "password123",
    role: 1,
    roleName: "Manager",
    Desc: "xyz",
    status: "Inactive",
    img:"assets/img/profiles/profile.png",
  },
  {
    userName: "JaneSmith",
    Phone: "5559876543",
    Email: "janesmith@example.com",
    fPass: "letmein",
    cnfPass: "letmein",
    role: 2,
    Desc: "xyz",
    roleName: "Admin",
    status: "Active",
    img:"assets/img/profiles/profile-01.png",

  },
  {
    userName: "MikeJohnson",
    Phone: "5555555555",
    Email: "mike@example.com",
    fPass: "securepass",
    cnfPass: "securepass",
    role: 3,
    Desc: "xyz",
    roleName: "Developer",
    status: "Inactive",
    img:"assets/img/profiles/profile-02.png",
  },
  {
    userName: "EmilyBrown",
    Phone: "5551112222",
    Email: "emilybrown@example.com",
    fPass: "password",
    Desc: "xyz",
    cnfPass: "password",
    status: "Active",
    role: 4,
    roleName: "Designer",
    img:"assets/img/profiles/profile-03.png",

  },
  {
    userName: "DavidWilson",
    Phone: "5554443333",
    Email: "david@example.com",
    fPass: "davidpass",
    status: "Active",
    cnfPass: "davidpass",
    role: 5,
    Desc: "xyz",
    roleName: "Analyst",
    img:"assets/img/profiles/profile.png",

  },
  {
    userName: "SarahLee",
    status: "Inactive",
    Phone: "5557778888",
    Email: "sarahlee@example.com",
    fPass: "ilovesarah",
    cnfPass: "ilovesarah",
    role: 6,
    Desc: "xyz",
    roleName: "Engineer",
    img:"assets/img/profiles/profile-03.png",

  },
  {
    userName: "ChrisTaylor",
    Phone: "5556669999",
    Email: "chris@example.com",
    status: "Active",
    fPass: "chrispass",
    cnfPass: "chrispass",
    role: 7,
    Desc: "xyz",
    roleName: "Coordinator",
    img:"assets/img/profiles/profile-02.png",

  },
  {
    userName: "AmandaJones",
    Phone: "5552223333",
    Email: "amanda@example.com",
    fPass: "amandapassword",
    status: "Inactive",
    cnfPass: "amandapassword",
    role: 8,
    Desc: "xyz",
    roleName: "Specialist",
    img:"assets/img/profiles/profile-01.png",

  },
  {
    userName: "MarkDavis",
    status: "Active",
    Phone: "5558887777",
    Email: "mark@example.com",
    fPass: "markpass",
    cnfPass: "markpass",
    role: 9,
    Desc: "xyz",
    roleName: "Consultant",
    img:"assets/img/profiles/profile.png",

  },
  {
    userName: "LauraWhite",
    Phone: "5553334444",
    Email: "laura@example.com",
    status: "Active",
    fPass: "laurapass",
    cnfPass: "laurapass",
    role: 10,
    Desc: "xyz",
    roleName: "Supervisor",
    img:"assets/img/profiles/profile-03.png",

  },
];